baseurl = "https://tellme.tokyo"
languageCode = "ja-jp"
title = "tellme.tokyo"
copyright = "Copyright &copy; {year} BABAROT All Right Reserved."
googleAnalytics = "UA-44183504-2"
publishDir = "docs"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "tellme.tokyo"
keywords = ["b4b4r07", "babarot"]
author = "b4b4r07"
profile = "profile.jpg"
website = "https://tellme.tokyo"
sharingicons = true
displayauthor = false
displayoldlink = true
readmore = false

[params.permalinks]
post = "/post/:year/:month/:day/:filename/"

[params.sharing]
twitter = true
hatebu = true
pocket = false

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/b4b4r07"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/b4b4r07"
fa_icon = "fa-twitter"

[outputFormats]
  [outputFormats.RSS]
    baseName = "feed"
