baseurl = "https://tellme.tokyo"
uglyURLs = false
languageCode = "ja-jp"
title = "tellme.tokyo"
theme = "tokyo"
copyright = "Copyright &copy; 2017 BABAROT All Right Reserved."

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "tellme.tokyo"
keywords = ["keyword 1", "keyword 2", "keyword 3"]
author = "b4b4r07"
profile = "profile.jpg"
website = "https://tellme.tokyo"
sharingicons = true
displayauthor = false
readmore = false

[params.permalinks]
post = "/post/:year/:month/:day/:filename/"

[params.sharing]
twitter = true
hatebu = true
pocket = false

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/b4b4r07"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/b4b4r07"
fa_icon = "fa-twitter"
